#!/usr/bin/env python3
"""
Game prediction engine: point spread, total, win probability, and a
style-matchup readout.

WHAT MOVES THE NUMBER, AND WHAT DOES NOT
----------------------------------------
Everything in this file is separated into effects that shift the predicted
MEAN and diagnostics that do not. That split is not stylistic -- it was
measured on this project's own 2023-2025 data (see experiments/):

  MOVES THE MEAN
    * opponent-adjusted OFF/DEF ridge ratings        (the whole model)
    * home field advantage, fitted as a coefficient  (+3.2 to +3.5 pts)
    * starting-QB adjustment, when a change is known (see qb_adjust)

  DOES **NOT** MOVE THE MEAN -- DIAGNOSTIC ONLY
    * pass-offense vs pass-defense "matchup" interaction. Tested directly:
      t = -0.39, R^2 = 0.0001 against out-of-sample residuals. All style
      interaction terms together moved residual std by 0.03 points. It is
      noise. It is displayed because it is genuinely interesting context and
      because it was asked for, but it is NOT allowed to touch the spread.

SIMULATION
----------
Scores are generated by a drive-based multinomial: each possession ends in a
touchdown, a field goal, or nothing. Compared against 2764 real games this
halves key-number error versus drawing from a Normal (real football piles up
on margins of 3 and 7, which continuous noise smears away), while matching
the observed mean and variance. See experiments/sim_distribution_test.py.

Noise is calibrated from OUT-OF-SAMPLE backtest residuals (data/calibration.json).
The in-sample figure understates real game variance by ~15% and would make
every win probability overconfident.
"""

import json
import os

import numpy as np
import pandas as pd

import cfb_ratings as R

from paths import DATA_DIR  # frozen-aware; see paths.py
DEFAULT_SIMS = 20000

# Drive-model parameters, chosen against the empirical score distribution.
MEAN_DRIVES = 12.0
SD_DRIVES = 1.3
FG_RATIO = 0.45          # E[FG drives] / E[TD drives]
PAT_RATE = 0.95
# Expected points of a touchdown drive INCLUDING the extra point. An earlier
# version derived drive probabilities assuming a TD is worth a flat 7.0 while
# the score generator paid 6 + Bernoulli(PAT_RATE) -- expected 6.95 -- which
# left the simulated mean ~0.3 points under the target for high-scoring teams.
TD_PTS = 6.0 + PAT_RATE
FALLBACK_SIGMA = 11.5    # out-of-sample per-team score sigma
# sigma(exp) = a + b*exp, fitted directly on the 1,853 out-of-sample backtest
# residuals (2026-08 refit; binned sd regression gives 8.14 + 0.117*exp).
# Earlier constants (6.56 + 0.097*exp) were ~21% low in absolute level and
# only correct after the blend rescale in simulate(); these are honest on
# their own, and the blend multiplier now sits near 1.0 instead of 1.26.
SIGMA_INTERCEPT = 8.14
SIGMA_SLOPE = 0.117
# Softplus score floor, fitted out-of-sample -- see score_floor()
FLOOR_C = 3.0
FLOOR_S = 4.0

# First-year head coach: measured on the 2024-2025 walk-forward residuals,
# a team with a new head coach underperforms the rating model's expectation
# by ~1.5 points of margin (2024: beta -1.63, t -1.84; 2025: beta -1.43,
# t -1.72; pooled t -2.52 across 693 affected games). It replicated in both
# directions of a fit-one-season/apply-to-the-other holdout (RMSE -0.06 and
# -0.07 on affected games), which is the replication bar every other
# situational factor failed. NOTE: the market prices this fully (incremental
# to the closing line t = -0.66), so it improves PROJECTIONS, not bets.
# Applied margin-only: half to each side, so totals are untouched.
COACH_CHANGE_MARGIN = -1.5


def load_calibration(path=None):
    path = path or os.path.join(DATA_DIR, "calibration.json")
    if not os.path.exists(path):
        return {"score_resid_std": FALLBACK_SIGMA, "resid_corr": 0.0,
                "margin_resid_std": 16.0, "source": "fallback (run backtest.py)"}
    with open(path, encoding="utf-8") as f:
        c = json.load(f)
    oos = c.get("out_of_sample", {})
    # NOTE: this whitelist must carry EVERY key a consumer needs. It silently
    # dropped edge_shrinkage once, which disabled all market calibration in
    # run_report.py -- the factors were fitted and written to disk but never
    # reached the report, so every bet call fell through to the uncalibrated
    # "NO BET" path. It failed safe, but it failed silently. Anything added to
    # calibration.json must be added here too.
    return {
        "score_resid_std": oos.get("score_resid_std", FALLBACK_SIGMA),
        "resid_corr": oos.get("resid_corr", 0.0),
        "margin_resid_std": oos.get("margin_resid_std", 16.0),
        "su_accuracy": oos.get("su_accuracy"),
        "total_calibration": c.get("total_calibration"),
        "edge_shrinkage": c.get("edge_shrinkage"),
        "total_edge_shrinkage": c.get("total_edge_shrinkage"),
        "fcs_augmentation": c.get("fcs_augmentation"),
        "coach_adjustment": c.get("coach_adjustment"),
        "source": "data/calibration.json (walk-forward out-of-sample)",
        # DELIBERATELY NOT FORWARDED: "clv_diagnostic" and "validation_gate".
        # These are monitoring statistics, not calibration. CLV is an upper
        # bound on edge rather than a substitute for it (+0.27 pts measured
        # against the 0.90 pts needed to break even at -110), and the gate is
        # already applied upstream -- evaluate_vs_market.py zeroes
        # shrink_factor itself when the gate fails, so the report reads the
        # gated number and never needs to re-derive it. This is an intentional
        # omission, NOT the silent-drop bug described above.
    }


def calibrate_total(raw_total, calib):
    """Shrink a raw projected total toward the league mean.

    The unshrunk total model is measurably worse than predicting the league
    average (see backtest.fit_total_calibration). Rating errors cancel in a
    margin but accumulate in a total, so totals must be pulled in. This is
    applied to the simulated distribution as a whole -- both the central
    estimate and the interval -- so the reported spread of outcomes shrinks
    with it rather than staying misleadingly wide.
    """
    tc = (calib or {}).get("total_calibration")
    if not tc or tc.get("slope") is None:
        return raw_total, False
    return tc["slope"] * np.asarray(raw_total, dtype=float) + tc["intercept"], True


# ---------------------------------------------------------------------------
# Expected scores
# ---------------------------------------------------------------------------

def score_floor(x, c=FLOOR_C, s=FLOOR_S):
    """Soft floor on a projected score.

    The rating model is linear, so against a badly overmatched opponent it
    happily extrapolates to two or even negative points. Real football does
    not do that: measured out-of-sample, teams projected below 5 points
    actually scored 7.5 on average, and teams projected 5-10 scored 10.3.
    There is a hard floor in the sport -- garbage-time drives, defensive and
    special-teams scores, and opponents emptying the bench all put points on
    the board even in a rout.

    A softplus is the right shape: it converges to the identity for normal
    projections (above ~20 points it is indistinguishable) and bends smoothly
    up toward `c` at the bottom, with no kink to distort the middle.

        f(x) = c + s * log(1 + exp((x - c) / s))

    Fitted on 1,853 out-of-sample games. Applying it improves BOTH margin
    (15.976 -> 15.949 RMSE) and total (16.672 -> 16.609), and removes a
    5.6-point bias in the lowest projection bucket.
    """
    x = np.asarray(x, dtype=float)
    return c + s * np.log1p(np.exp(np.clip((x - c) / s, -50, 50)))


def expected_scores(ratings, home, away, neutral=False, qb_adj=None, floor=True,
                    margin_adj=0.0):
    """Model mean scores. qb_adj maps team -> points added to that team's
    offense (negative for a downgrade at quarterback).

    margin_adj is a HOME-margin adjustment applied half to each side, so it
    moves the margin by exactly margin_adj and the total by zero. Used for
    the first-year-head-coach effect (see coach_margin_adj); anything with a
    measured margin effect but no measured totals effect belongs here rather
    than in qb_adj, which shifts the total too.
    """
    for t in (home, away):
        if not ratings.has(t):
            raise KeyError(f"no rating for {t!r}")
    s = 0.0 if neutral else 1.0
    adj_h = (qb_adj or {}).get(home, 0.0)
    adj_a = (qb_adj or {}).get(away, 0.0)
    eh = ratings.mu + ratings.off[home] - ratings.defn[away] + s * ratings.hfa / 2 + adj_h
    ea = ratings.mu + ratings.off[away] - ratings.defn[home] - s * ratings.hfa / 2 + adj_a
    if margin_adj:
        eh += margin_adj / 2.0
        ea -= margin_adj / 2.0
    if floor:
        return float(score_floor(eh)), float(score_floor(ea))
    return max(eh, 0.5), max(ea, 0.5)


# ---------------------------------------------------------------------------
# First-year head coach context (CFBD coaches files; leak-free by season)
# ---------------------------------------------------------------------------

def _norm_team(s):
    return (str(s).strip().replace("State", "St").replace("&", "and")
            .replace(".", "").replace("'", "").lower())


def load_coach_changes(seasons, data_dir=None):
    """{season: set of normalized team names with a FIRST-YEAR head coach}.

    A team counts as changed in season S when data/cfbd_coaches_{S}.csv and
    _{S-1}.csv both exist and name different head coaches for it. Coach lists
    for season S are published before season S kicks off, so using them for
    season S games is legitimate preseason information. Missing files degrade
    to an empty set (the adjustment silently no-ops), with a printed note so
    the absence is visible rather than silent.
    """
    import ast
    data_dir = data_dir or DATA_DIR
    by_year = {}
    for yr in sorted({s for s in seasons} | {s - 1 for s in seasons}):
        path = os.path.join(data_dir, f"cfbd_coaches_{yr}.csv")
        if not os.path.exists(path):
            continue
        try:
            c = pd.read_csv(path)
        except Exception:  # noqa: BLE001
            continue
        if "seasons" not in c.columns:
            continue
        m = {}
        for _, r in c.iterrows():
            try:
                yrs = ast.literal_eval(r["seasons"]) if isinstance(r["seasons"], str) else r["seasons"]
            except (ValueError, SyntaxError):
                continue
            for s in (yrs or []):
                if s.get("year") == yr and s.get("school"):
                    m[_norm_team(s["school"])] = f"{r.get('firstName')} {r.get('lastName')}"
        by_year[yr] = m
    out = {}
    for season in seasons:
        cur, prev = by_year.get(season), by_year.get(season - 1)
        if not cur or not prev:
            out[season] = set()
            print(f"  (coach adjustment: no coach data for {season}/{season-1}; "
                  f"skipping -- run fetch_cfbd.py to enable)")
            continue
        out[season] = {k for k, v in cur.items() if k in prev and prev[k] != v}
    return out


def coach_margin_adj(new_coach_set, home, away):
    """Home-margin adjustment for first-year head coaches.

    new_coach_set holds NORMALIZED names (see load_coach_changes). Returns
    COACH_CHANGE_MARGIN * (home_changed - away_changed): a home team with a
    new coach gets -1.5 of margin, an away team with one gives +1.5, both
    cancel. Zero when the set is empty or None.
    """
    if not new_coach_set:
        return 0.0
    h = 1.0 if _norm_team(home) in new_coach_set else 0.0
    a = 1.0 if _norm_team(away) in new_coach_set else 0.0
    return COACH_CHANGE_MARGIN * (h - a)


# ---------------------------------------------------------------------------
# Drive-based Monte Carlo
# ---------------------------------------------------------------------------

def target_sigma(exp_pts, a=SIGMA_INTERCEPT, b=SIGMA_SLOPE):
    """Per-team score sigma as a function of expected points.

    Fitted directly on the 1,853 out-of-sample backtest residuals: sd rises
    from ~8.3 for teams projected around 7 points to ~13.2 around 46. A mild
    slope, NOT proportionality -- a multiplicative noise model would imply a
    ~3.5x spread across that range instead of the observed ~1.6x, and would
    make favorites wildly more volatile than they really are.

    The bare output of this function is meant to be honest on its own (an
    earlier version was ~21% low and only correct after simulate()'s blend
    rescale). simulate() still applies the blend so the LEVEL always tracks
    the current calibration.json even if these constants go stale.
    """
    return np.maximum(a + b * np.asarray(exp_pts, dtype=float), 4.0)


def _drive_variance(exp_pts, mean_drives, sd_drives):
    """Analytic variance of the drive multinomial, so the additive form-noise
    term can be sized to make total variance hit the empirical target."""
    ppd = np.asarray(exp_pts, dtype=float) / mean_drives
    p_td = ppd / (TD_PTS + 3.0 * FG_RATIO)
    p_fg = p_td * FG_RATIO
    per_drive = (TD_PTS ** 2 * p_td * (1 - p_td) + 9.0 * p_fg * (1 - p_fg)
                 - 2 * TD_PTS * 3.0 * p_td * p_fg)
    var_counts = mean_drives * np.maximum(per_drive, 0.0)
    var_pace = (ppd ** 2) * (sd_drives ** 2)   # variance from drive-count spread
    return var_counts + var_pace


def _drive_scores(eff_pts, drives, rng):
    """Simulate one side's score from possession outcomes."""
    n = len(eff_pts)
    eff = np.maximum(eff_pts, 0.5)
    ppd = eff / drives
    p_td = ppd / (TD_PTS + 3.0 * FG_RATIO)
    p_fg = p_td * FG_RATIO
    tot = p_td + p_fg
    scale = np.where(tot > 0.92, 0.92 / np.maximum(tot, 1e-9), 1.0)
    p_td, p_fg = p_td * scale, p_fg * scale

    maxd = int(drives.max())
    u = rng.random((maxd, n))
    live = np.arange(maxd)[:, None] < drives[None, :]
    td = ((u < p_td) & live).sum(axis=0)
    fg = ((u >= p_td) & (u < p_td + p_fg) & live).sum(axis=0)
    pat = rng.random((maxd, n)) < PAT_RATE
    made = ((np.arange(maxd)[:, None] < td[None, :]) & pat).sum(axis=0)
    return 6.0 * td + made + 3.0 * fg


def simulate(exp_h, exp_a, n_sims=DEFAULT_SIMS, sigma=None, seed=None,
             mean_drives=MEAN_DRIVES, sd_drives=SD_DRIVES):
    """Monte Carlo one matchup. Returns simulated (home, away) score arrays.

    Total per-team variance is composed of two parts:
      1. intrinsic possession variance from the drive multinomial, and
      2. additive game-to-game "form" noise (weather, injury, motivation,
         officiating) sized so the total matches the empirically measured
         sigma for a team with that projected score.
    """
    rng = np.random.default_rng(seed)

    drives = np.clip(np.round(rng.normal(mean_drives, sd_drives, n_sims)), 8, 18).astype(int)

    out = []
    for exp in (exp_h, exp_a):
        tgt = float(target_sigma(exp))
        if sigma is not None:
            # blend the global out-of-sample sigma with the score-dependent
            # curve, keeping the curve's shape but honoring the measured level
            tgt = tgt * (sigma / float(target_sigma(26.7)))
        intrinsic = float(_drive_variance(exp, mean_drives, sd_drives))
        s_form = float(np.sqrt(max(tgt ** 2 - intrinsic, 0.0)))
        eff = np.full(n_sims, float(exp)) + rng.normal(0.0, s_form, n_sims)
        out.append(_drive_scores(eff, drives, rng))
    h, a = out

    # college football does not end in a tie -- resolve with an OT coin flip
    tied = h == a
    if tied.any():
        idx = np.flatnonzero(tied)
        home_wins = rng.random(idx.size) < 0.5
        h = h.copy(); a = a.copy()
        h[idx[home_wins]] += 3.0
        a[idx[~home_wins]] += 3.0
    return h, a


def summarize(home, away, sim_h, sim_a, calib=None):
    """Turn a simulated distribution into the numbers a bettor actually wants.

    The MARGIN is used as simulated. The TOTAL is shrunk toward the league
    mean first -- unshrunk totals are measurably worse than guessing the
    average (see calibrate_total).
    """
    margin = sim_h - sim_a
    total_raw = sim_h + sim_a
    total, total_was_calibrated = calibrate_total(total_raw, calib)
    p_home = float((margin > 0).mean() + 0.5 * (margin == 0).mean())

    # Three distinct "spread" numbers -- they are NOT the same thing:
    #   mean   : the model's expected margin (what a projection should quote)
    #   median : the middle outcome, less pulled by blowouts
    #   fair   : the line at which cover probability is 50% (what a book quotes)
    mean_margin = float(margin.mean())
    median_margin = float(np.median(margin))
    fair_line = float(np.percentile(margin, 50))

    return {
        "home": home, "away": away,
        "exp_home": float(sim_h.mean()), "exp_away": float(sim_a.mean()),
        "mean_margin": mean_margin,
        "median_margin": median_margin,
        "fair_spread": fair_line,
        "spread_str": spread_string(home, away, fair_line),
        "home_win_prob": p_home, "away_win_prob": 1.0 - p_home,
        "total": float(np.mean(total)),
        "total_median": float(np.median(total)),
        "total_raw": float(np.mean(total_raw)),
        "total_calibrated": bool(total_was_calibrated),
        "margin_p10": float(np.percentile(margin, 10)),
        "margin_p90": float(np.percentile(margin, 90)),
        "total_p10": float(np.percentile(total, 10)),
        "total_p90": float(np.percentile(total, 90)),
        "p_home_by_3plus": float((margin >= 3).mean()),
        "p_home_by_7plus": float((margin >= 7).mean()),
        "p_within_3": float((np.abs(margin) <= 3).mean()),
        "p_within_7": float((np.abs(margin) <= 7).mean()),
    }


def spread_string(home, away, margin):
    """Book-style line, rounded to the nearest half point."""
    m = round(margin * 2) / 2.0
    if m == 0:
        return f"PK ({home} / {away})"
    if m > 0:
        return f"{home} -{m:g}"
    return f"{away} -{-m:g}"


def cover_probability(sim_h, sim_a, line_home):
    """P(home covers) for a line quoted from the home side, e.g. -7.5."""
    margin = sim_h - sim_a
    adj = margin + line_home
    push = float((adj == 0).mean())
    win = float((adj > 0).mean())
    return {"home_cover": win, "push": push, "away_cover": 1.0 - win - push}


# ---------------------------------------------------------------------------
# Style matchup -- DIAGNOSTIC ONLY (measured to have no predictive signal)
# ---------------------------------------------------------------------------

STYLE_FIELDS = [
    ("off_pass_rate", "pass-play rate", True),
    ("off_ypp", "yards per play", True),
    ("off_yardsPerPassAttempt", "yards per pass att", True),
    ("off_yardsPerRushAttempt", "yards per rush att", True),
    ("off_plays_pg", "plays per game (tempo)", True),
]


def load_team_styles(path=None, season=None):
    path = path or os.path.join(DATA_DIR, "team_stats.csv")
    if not os.path.exists(path):
        return None
    ts = pd.read_csv(path)
    if season is not None and "season" in ts.columns:
        sub = ts[ts["season"] == season]
        if len(sub):
            ts = sub
    else:
        ts = ts[ts["season"] == ts["season"].max()]
    ts["team_id"] = ts["team_id"].astype(str)
    return ts


def _z(series):
    s = pd.to_numeric(series, errors="coerce")
    sd = s.std(ddof=0)
    return (s - s.mean()) / sd if sd and sd > 0 else s * 0.0


def style_report(styles, home_id, away_id, home, away):
    """Quantify how stylistically opposed two teams are, and where the
    sharpest unit mismatches sit.

    Two distinct numbers, deliberately:
      * opposition index -- how DIFFERENT the two teams are (a fast spread
        offense against a slow grinding one). Symmetric, no favorite implied.
      * unit mismatches  -- DIRECTIONAL: this offense's strength against that
        defense's weakness, in standard deviations.

    Neither figure adjusts the spread. Measured effect on out-of-sample
    residuals was statistically indistinguishable from zero.
    """
    if styles is None:
        return None
    s = styles.copy()
    for col in ["off_pass_rate", "off_ypp", "off_yardsPerPassAttempt",
                "off_yardsPerRushAttempt", "off_plays_pg",
                "def_yardsPerPassAttempt", "def_yardsPerRushAttempt", "def_ypp"]:
        if col in s.columns:
            s["z_" + col] = _z(s[col])

    h = s[s["team_id"] == str(home_id)]
    a = s[s["team_id"] == str(away_id)]
    if h.empty or a.empty:
        return None
    h, a = h.iloc[0], a.iloc[0]

    dims = []
    for col, label, _ in STYLE_FIELDS:
        zc = "z_" + col
        if zc in s.columns and pd.notna(h.get(zc)) and pd.notna(a.get(zc)):
            dims.append((label, float(h[zc]), float(a[zc])))

    opposition = float(np.sqrt(np.mean([(hv - av) ** 2 for _, hv, av in dims]))) if dims else None

    mismatches = []
    pairs = [
        ("pass", "z_off_yardsPerPassAttempt", "z_def_yardsPerPassAttempt"),
        ("rush", "z_off_yardsPerRushAttempt", "z_def_yardsPerRushAttempt"),
        ("overall", "z_off_ypp", "z_def_ypp"),
    ]
    for label, ocol, dcol in pairs:
        if ocol in s.columns and dcol in s.columns:
            # def_ z is "yards allowed", so a HIGH z is a WEAK defense
            if pd.notna(h.get(ocol)) and pd.notna(a.get(dcol)):
                mismatches.append({
                    "unit": f"{home} {label} offense vs {away} {label} defense",
                    "edge_sd": round(float(h[ocol] + a[dcol]) / 2.0, 2),
                })
            if pd.notna(a.get(ocol)) and pd.notna(h.get(dcol)):
                mismatches.append({
                    "unit": f"{away} {label} offense vs {home} {label} defense",
                    "edge_sd": round(float(a[ocol] + h[dcol]) / 2.0, 2),
                })
    mismatches.sort(key=lambda m: -abs(m["edge_sd"]))
    return {
        "opposition_index": round(opposition, 2) if opposition is not None else None,
        "dimensions": [{"dimension": d, "home_z": round(hv, 2), "away_z": round(av, 2),
                        "gap_sd": round(hv - av, 2)} for d, hv, av in dims],
        "mismatches": mismatches[:4],
    }


# ---------------------------------------------------------------------------
# Top-level prediction
# ---------------------------------------------------------------------------

def predict_game(ratings, home, away, neutral=False, n_sims=DEFAULT_SIMS,
                 calib=None, styles=None, home_id=None, away_id=None,
                 qb_adj=None, line=None, seed=None, margin_adj=0.0):
    calib = calib or load_calibration()
    eh, ea = expected_scores(ratings, home, away, neutral=neutral, qb_adj=qb_adj,
                             margin_adj=margin_adj)
    sim_h, sim_a = simulate(eh, ea, n_sims=n_sims,
                            sigma=calib["score_resid_std"], seed=seed)
    out = summarize(home, away, sim_h, sim_a, calib=calib)
    out["neutral_site"] = neutral
    out["model_exp_home"] = eh
    out["model_exp_away"] = ea
    out["qb_adj"] = dict(qb_adj or {})
    if line is not None:
        out["cover"] = cover_probability(sim_h, sim_a, line)
        out["line"] = line
    if styles is not None and home_id is not None and away_id is not None:
        out["style"] = style_report(styles, home_id, away_id, home, away)
    return out


def format_game(p, calib=None):
    """Human-readable per-game card."""
    L = []
    site = "neutral site" if p.get("neutral_site") else f"at {p['home']}"
    L.append(f"{p['away']}  at  {p['home']}   ({site})")
    L.append("-" * 66)
    L.append(f"  Projected score : {p['home']} {p['exp_home']:.1f} - "
             f"{p['away']} {p['exp_away']:.1f}")
    L.append(f"  POINT SPREAD    : {p['spread_str']}")
    L.append(f"  PROJECTED TOTAL : {p['total']:.1f}   "
             f"(80% range {p['total_p10']:.0f} - {p['total_p90']:.0f})")
    L.append("")
    L.append(f"  Win probability : {p['home']} {p['home_win_prob']*100:.1f}%  |  "
             f"{p['away']} {p['away_win_prob']*100:.1f}%")
    L.append(f"  Margin (home)   : mean {p['mean_margin']:+.1f}, "
             f"median {p['median_margin']:+.1f}, "
             f"80% range {p['margin_p10']:+.0f} to {p['margin_p90']:+.0f}")
    L.append(f"  Close-game odds : within 3 pts {p['p_within_3']*100:.0f}%, "
             f"within 7 pts {p['p_within_7']*100:.0f}%")
    if "cover" in p:
        c = p["cover"]
        L.append(f"  vs line {p['line']:+g}    : {p['home']} covers "
                 f"{c['home_cover']*100:.1f}%, push {c['push']*100:.1f}%, "
                 f"{p['away']} covers {c['away_cover']*100:.1f}%")
    if p.get("qb_adj"):
        for t, v in p["qb_adj"].items():
            if v:
                L.append(f"  QB adjustment   : {t} {v:+.1f} pts")

    st = p.get("style")
    if st:
        L.append("")
        L.append("  STYLE MATCHUP (diagnostic only -- does NOT move the spread above)")
        if st.get("opposition_index") is not None:
            oi = st["opposition_index"]
            desc = ("very similar styles" if oi < 0.6 else
                    "moderately different" if oi < 1.2 else
                    "stylistic opposites")
            L.append(f"    style opposition index : {oi:.2f} sd  ({desc})")
        for m in st.get("mismatches", [])[:3]:
            L.append(f"    {m['unit']:<52} {m['edge_sd']:+.2f} sd")
    return "\n".join(L)
